name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the backend folder
            cd /home/ec2-user/firstapp
            
            # Pull the latest code
            git pull origin main
            
            # Install any new packages
            npm install
            
            # Restart the load-balanced workers
            pm2 restart all